language: php
php:
# - '5.4'
  - '5.5'


env:
  - DB=mysql
  
matrix:
  include:
    - php: 5.5
    - evn: DB=mysql
  allow_failures:
    - php: 5.5
    
#set before scirpt 
#before_script:

# use the $DB env variable to determine the phpunit.xml to use
#script: phpunit --configuration phpunit_$DB.xml --coverage-text
script: ./my.sh
